-- create database user
CREATE ROLE loms WITH
	LOGIN
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'loms';

-- create database
CREATE DATABASE loms
    WITH
    OWNER = loms
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

-- create table
CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) NOT NULL,
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

-- create table message
-- CREATE TABLE public.messages
-- (
--     id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
--     message character varying(255) NOT NULL,
--     CONSTRAINT messages_pkey PRIMARY KEY (id)
-- )

ALTER TABLE public.users OWNER to loms;